---
- name: Provision Desktop
  hosts: all

  collections:
    - kewlfft.aur

  tasks:
    - include_tasks: tasks/system_prerequisites.yml
    - include_tasks: tasks/dotfiles_repo.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/spacemacs.yml
