- name: install emacs
  become: yes
  community.general.pacman:
    state: present
    name: emacs

- name: install spacemacs
  become: yes
  become_user: '{{ USERNAME }}'
  ansible.builtin.git:
    repo: https://github.com/syl20bnr/spacemacs.git
    dest: ~/.emacs.d
    clone: yes

- name: apply spacemacs configuration
  become: yes
  become_user: '{{ USERNAME }}'
  ansible.builtin.git:
    repo: https://github.com/nikolovdeyan/Spacemacs-Configuration.git
    dest: ~/.spacemacs.d
    clone: yes

- name: delete .spacemacs file
  become: yes
  become_user: '{{ USERNAME }}'
  file:
    state: absent
    path: ~/.spacemacs
