- name: set hostname
  become: yes
  command: hostnamectl set-hostname "{{ HOSTNAME }}"

- name: update system
  become: yes
  command: pacman -Syu --noconfirm

- name: install system prerequisites
  become: yes
  community.general.pacman:
    state: present
    name:
      - wget
      - arandr
      - htop
      - alsa-utils
      - vim
      - xorg-setxkbmap

- name: install system prerequisites [AUR]
  become: yes
  kewlfft.aur.aur:
    use: yay
    name:
      - dropbox

- name: install system fonts
  become: yes
  community.general.pacman:
    state: present
    name:
      - otf-fantasque-sans-mono
      - ttc-iosevka
