- name: set hostname
  become: yes
  command: hostnamectl set-hostname "{{ HOSTNAME }}"

- name: update system
  become: yes
  command: pacman -Syu --noconfirm

- name: install system prerequisites
  become: yes
  community.general.pacman:
    state: present
    name:
      - wget
      - arandr
      - htop
      - alsa-utils
      - vim
      - xorg-setxkbmap
      - konsole
      - rofi
      - nitrogen
    register: prereqs_result

- debug:
    var: prereqs_result.stdout_lines

- name: install system prerequisites [AUR]
  become: yes
  become_user: '{{ USERNAME }}'
  kewlfft.aur.aur:
    use: yay
    state: present
    name:
      - dropbox
      - polybar
      - keepass
      - rofi-file-browser-extended-git
    register: prereqs_aur_result

- debug:
    var: prereqs_result_aur.stdout_lines

- name: install system fonts
  become: yes
  community.general.pacman:
    state: present
    name:
      - otf-fantasque-sans-mono
      - ttc-iosevka
