- name: install zsh
  become: yes
  community.general.pacman:
    name: zsh
    state: present

- name: clone oh-my-zsh repository
  become: yes
  become_user: '{{ USERNAME }}'
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    clone: yes

- name: copy oh-my-zsh default .zshrc
  become: yes
  become_user: '{{ USERNAME }}'
  ansible.builtin.copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
    remote_src: yes

- name: make zsh the default shell for the user
  become: yes
  user:
    name: '{{ USERNAME }}'
    shell: /usr/bin/zsh
