- name: install zsh
  package:
    state: present
    name:
      - zsh

- name: clone oh-my-zsh repository
  become: yes
  become_user: '{{ USERNAME }}'
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    clone: yes

- name: copy oh-my-zsh default .zshrc
  become: yes
  become_user: '{{ USERNAME }}'
  ansible.builtin.copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
    remote_src: yes
    
- name: change shell to zsh
  become: yes
  become_user: '{{ USERNAME }}'
  ansible.builtin.command: "chsh -s $(which zsh)"
