- name: install zsh
  package:
    state: present
    name:
      - zsh

- name: instal oh-my-zsh
  become: yes
  become_user: '{{ USERNAME }}'
  ansible.builtin.command:
    chdir: ~
    cmd: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"

