- name: install zsh
  package:
    state: present
    name:
      - zsh

- name: instal oh-my-zsh
  become: yes
  become_user: '{{ USERNAME }}'
  ansible.builtin.command:
    chdir: ~
    cmd: sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended

